# Generated by Django 4.1.4 on 2023-01-06 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, unique=True, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Клас',
                'verbose_name_plural': 'Класи',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to='photo/%Y/%m/%d/', verbose_name='Обкладинка')),
                ('pdf_file', models.FileField(null=True, upload_to='pdffiles/', verbose_name='Файл книги')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата змінення')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публікація')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.group', verbose_name='Клас')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['group', 'title'],
            },
        ),
    ]
