# Generated by Django 4.1.4 on 2023-01-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='pdffiles/', verbose_name='PDF файл'),
        ),
    ]
